### ISSUE TITLE
laz-perf can't open the files it creates for compressed point-format > 5

### ISSUE THREAD

**Issue by froody** [hobu/laz-perf#100]
When writing point-format > 5, laz-perf sets the `compressor` field of `laz_vlr` to 3 ([see code](https://github.com/hobu/laz-perf/blob/2.0.5/cpp/lazperf/vlr.cpp#L75)). When reading however, there is an explicit requirement that `compressor == 2` ([see code](https://github.com/hobu/laz-perf/blob/2.0.5/cpp/lazperf/io.cpp#L199)). Commenting out the check causes a crash. This means that any laz file generated by laz-perf with point-format > 5 requires laszip to decompress it.

**Comment by abellgithub** [comment]
As you have found, the code that exists that wasn't part of the compression processing itself is weak. It really only existed for testing the compression code.  I've made more changes that I'll push when it's done and I'll try to make sure this issue is part of the PR.

**Comment by abellgithub** [comment]
Fixed by #101
