### ISSUE TITLE
Laz Spec

### ISSUE THREAD

**Issue by timodwhit** [hobu/laz-perf#105]
In one of @hobu's emails to the pdal community: 

> [there isn't a] LAZ specification beyond the LASzip code

With Martin's passing, does it make sense to harden the laz spec and start defining it within the community and trying to have a standard similar to copc?

This would obviously be difficult without full deprecation or access to laszip (not sure the state of that) and with the current landscape of laz in the wild. However, would it make sense to standardize a 1.4.1 spec and start moving towards something? 

I opened this ticket here since lazperf is now tied to pdal. However, if it should live elsewhere, feel free to let me know.

**Comment by hobu** [comment]
> With Martin's passing, does it make sense to harden the laz spec and start defining it within the community and trying to have a standard similar to copc?

Yes, but a COPC-style simple web page spec is not going to be sufficient for LAZ. The model is *very* intricate, and there's multiple encoders embedded in LASzip as well. I suppose the way forward would be to **only** specify LAZ 1.4.

That said, I have some actions going privately on the LAZ specification topic that I am not yet ready to announce. Let's rewake this thread in a month or two.

**Comment by timodwhit** [comment]
@abellgithub Where should this live? I agree it is out of spec for this hardware...
