### ISSUE TITLE
portable_endian.hpp includes windows.h - which tends to cause several issues in including files

### ISSUE THREAD

**Issue by m-schuetz** [hobu/laz-perf#109]
Including windows.h has the tendency to break code, e.g.:
* https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std

and often also in not easily addressable ways:
* https://developercommunity.visualstudio.com/t/error-c2872-byte-ambiguous-symbol/93889

Trying to include laz-perf in PotreeConverter is a pretty difficult experience due to that. Would you accept a PR that moves the ```#   include <winsock2.h>``` from ```portable_endian.hpp``` into a separate ```portable_endian.cpp``` file? As long as the include is in a cpp file, it won't cause issues.

Right now I'm having succes after replacing 

```
 #       define htobe16 htons
 #       define htole16(x) (x)
 #       define be16toh ntohs
 #       define le16toh(x) (x)

 #       define htobe32 htonl
 #       define htole32(x) (x)
 #       define be32toh ntohl
 #       define le32toh(x) (x)

 #       define htobe64 htonll
 #       define htole64(x) (x)
 #       define be64toh ntohll
 #       define le64toh(x) (x)
```

with

```
inline uint16_t htobe16(uint16_t value);
inline uint16_t htole16(uint16_t value) {return value;};
inline uint16_t be16toh(uint16_t value);
inline uint16_t le16toh(uint16_t value) {return value;};

inline uint32_t htobe32(uint32_t value);
inline uint32_t htole32(uint32_t value) {return value;};
inline uint32_t be32toh(uint32_t value);
inline uint32_t le32toh(uint32_t value) {return value;};

inline uint64_t htobe64(uint64_t value);
inline uint64_t htole64(uint64_t value) {return value;};
inline uint64_t be64toh(uint64_t value);
inline uint64_t le64toh(uint64_t value) {return value;};

```

And then implementing the functions that rely on the windows api in ```portable_endian.cpp``` as follows:

```
inline uint16_t htobe16(uint16_t value){
	return htons(value);
}

inline uint16_t be16toh(uint16_t value){
	return ntohs(value);
}

inline uint32_t htobe32(uint32_t value){
	return htonl(value);
}

inline uint32_t be32toh(uint32_t value){
	return ntohl(value);
}

inline uint64_t htobe64(uint64_t value){
	return htonll(value);
}

inline uint64_t be64toh(uint64_t value){
	return ntohll(value);
}
```

**Comment by abellgithub** [comment]
What are you including in your code that is bringing in `portable_endian`? I don't see where this would be happening.

More generally speaking, if you're running on Windows, it seems reasonable for your code to work with `Windows.h`. The issues you linked have pretty simple workarounds, though MS should have been hung long ago for #define'ing `min` and `max`.

**Comment by m-schuetz** [comment]
I've tried following the https://github.com/hobu/laz-perf/blob/master/cpp/examples/point10.cpp example, for which I've also needed to include streams.hpp. Not sure why point10.cpp doesn't need that include, but I can't use MemoryStream without including it. 

On the other hand, I might not actually need MemoryStream and streams.hpp since I probably should follow the readlaz.cpp example.

> More generally speaking, if you're running on Windows, it seems reasonable for your code to work with Windows.h.

I've had so many problems with windows.h that I've never been able to solve so that I started using it only in cpp files. The min/max error isn't really the problem, it's the "byte = ambiguous" that I wasn't able to solve even with the suggested fixes in the link above.

**Comment by hobu** [comment]
Were you able to make progress?

**Comment by m-schuetz** [comment]
Have to focus on another projects for the next couple of days, but will let you know about progress.

**Comment by m-schuetz** [comment]
Closed, because I've just been using it wrong.
