### ISSUE TITLE
clarify licensing

### ISSUE THREAD

**Issue by strk** [hobu/laz-perf#11]
I saw COPYING file is LGPL2.1, but nowhere it's said it is the license applied to the codebase.
For example, is it LGPL2 "or any later version" or strictly LGPL2 ?

Mentioning in the README (or in a separate LICENSE file) might be enough, although most guides recommend to write a short header in each source file...

**Comment by strk** [comment]
Some headers do exist in the core library, but do not say anything about version of the license:
https://github.com/verma/laz-perf/blob/master/laz-perf/excepts.hpp

**Comment by hobu** [comment]
We may need to clean it up a bit, but lazperf is whatever LASzip is licensed as, which is LGPL2 IIRC.
