### ISSUE TITLE
A lot of debug output from LAZDEBUG

### ISSUE THREAD

**Issue by wonder-sk** [hobu/laz-perf#127]
Currently lazperf outputs a lot of debug output from LAZDEBUG macro when reading points unless NDEBUG is defined. It would be nicer if there would be an explicit macro to enable it (e.g. LAZPERF_DEBUG) rather than just using the generic NDEBUG.

Rationale: in a project like QGIS, one wants to run debug version of the code (without NDEBUG defined) but having lazperf output so much information is not desired. I know one could define NDEBUG compile options for lazperf source files even when compiling in debug mode, but opt-in approach to enable lazperf debug output would be much nicer...

**Comment by hobu** [comment]
Addressed in #129
