### ISSUE TITLE
missing pylazperfapi.cpp

### ISSUE THREAD

**Issue by becio** [hobu/laz-perf#36]
Hello,

I tried to compile the source code, along to other things I did:

_pip install -e "git+https://github.com/hobu/laz-perf#egg=lazperf&subdirectory=python"_

and I got this error:

_creating build/temp.linux-x86_64-3.4/lazperf                                                                                                                                                                            
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I. -I/home/lopocs/venv/lib/python3.4/site-packages/numpy/core/include -I/usr/include/python3.4m -I/home/lopocs/venv/include/python3.4m -c lazperf/pylazperfapi.cpp -o build/temp.linux-x86_64-3.4/lazperf/pylazperfapi.o -std=c++11 -g -O0                                  
x86_64-linux-gnu-gcc: error: lazperf/pylazperfapi.cpp: No such file or directory                                                                                                                                        
x86_64-linux-gnu-gcc: fatal error: no input files                                                                                                                                                                       
compilation terminated.                                                                                                                                                                                                 
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4_ 

Thanks

**Comment by hobu** [comment]
cython is required for generating the wrapper, but it might not be specified in setup.py.

**Comment by becio** [comment]
_pip install Cython_ solved.

Thanks
