### ISSUE TITLE
laz-perf python api documentation

### ISSUE THREAD

**Issue by themmes** [hobu/laz-perf#37]
Hi Howard,

If this implementation is more powerful than LASzip I would like it to read `.laz` files in my experiments. Could you maybe provide some guidance on how to use the python interface. From the tests I understand the usage for `.bin` files, but tests for `.laz` seem to be missing.

Hope to hear from you!

Tom

**Comment by hobu** [comment]
There is still work to do in laspy to bring this together. I have a branch that does it, but it is super rough.

https://github.com/hobu/laspy/tree/lazperf-decomp

**Comment by mwil** [comment]
What is the status of this? I would like to write out a LAZ file in laspy without shipping laszip.

**Comment by hobu** [comment]
Lots of work still needed. Happy to take a PR that finishes the implementation.

**Comment by mwil** [comment]
I don't even get what happens exactly in the test code for the compressor 😄

**Comment by abellgithub** [comment]
We're no longer supporting python.
