### ISSUE TITLE
portable_endian license

### ISSUE THREAD

**Issue by johanvdw** [hobu/laz-perf#47]
Currently, the portable endian license file does not carry a license. 
The version below however clearly states that it is in the public domain, which was confirmed by the author https://github.com/panzi/mathfun/issues/1 .
Perhaps it is better to link to this file (and merge emscripten changes back?).

https://gist.githubusercontent.com/panzi/6856583/raw/1eca2ab34f2301b9641aa73d1016b951fff3fc39/portable_endian.h

**Comment by hobu** [comment]
Please make a PR to address this, and I'll be happy to merge. As it happens, I just tagged 1.2.0 twenty minutes ago, so unfortunately you missed this latest release cycle.

**Comment by johanvdw** [comment]
Cool,

I'll do that.

**Comment by abellgithub** [comment]
I believe the file was copied verbatim from the source at the time.

This seems like marking things "Unclassified". It seems the default.

**Comment by hobu** [comment]
> This seems like marking things "Unclassified". It seems the default.

For license and lineage, especially with some distributions, they want things very explicit, or they will not allow the software into their distribution. For debian for laz-perf, we are still hung up on FastAC, and @rapidlasso's modifications of it, so I don't know that this matters.

**Comment by johanvdw** [comment]
I was indeed looking at licensing for (potential) integration into debian.

**Comment by abellgithub** [comment]
I considered becoming an attorney for about a month. Very glad I decided otherwise.
