### ISSUE TITLE
Cannot pip install

### ISSUE THREAD

**Issue by tmontaigu** [hobu/laz-perf#48]
I tried to install lazperf using pip but it did not work on either Windows or Linux.

I looked at the .tar.gz archive stored on Pypi and it is missing the .pxd file in lazperf folder
and it is also missing the actual laz-perf code which makes the wrapper fail to compile.

**Comment by hobu** [comment]
Can you suggest any patches that I would need to make to get good packages pushed to PyPI? I just invoked `python setup.py sdist` and `twine upload dist/lazperf-1.2.tar.gz`

**Comment by tmontaigu** [comment]
Hum, I tried running `python setup.py sdist` and the resulting tar.gz archive was good, I could install with `pip install lazperf-1.1.tar.gz` without changing anything so I don't know why the one on Pypi is missing files, something may have failed with the symbolic link when you ran it.

It doesn't work on windows  tho 🙄 , can I provide precompiled wheel packages instead?

**Comment by hobu** [comment]
please try the wheel I have uploaded.

https://pypi.python.org/packages/fd/ef/7c5a261c120b1804025324dedc4807868946ad27d1c570ad82a8bad91357/lazperf-1.1-cp36-cp36m-win_amd64.whl#md5=58e7bf08b5bae0151c9f68b273250757

**Comment by tmontaigu** [comment]
Thanks, it works although I have to do `pip install lazperf==1.1` because `pip install lazperf` will download the .tar.gz instead
