### ISSUE TITLE
can it also manipulate .las files ?

### ISSUE THREAD

**Issue by Auriejir** [hobu/laz-perf#64]
Hi, I'm looking for a decent ( C ) .las reader / writer, one that doesn't require to include half of the universe like liblas does and I must say that laz-perf is exactly what I was looking for... except that it's for .laz files.
How far is laz-perf from reading .las files ? is there any technical difficulty that prevented laz-perf from reading / writing .las files aside from it not being the point of the project at all ?
Or, maybe I just didn't looked hard enough... did I miss this part ?

I would be interested in any pointer regarding what would be left to do in order to be able to open either type of file seamlessly and if someone is interested, I will share the results once it's clean enough

**Comment by hobu** [comment]
I think it is out of scope for laz-perf to be a generic LAS format library. If you look at PDAL's LAS capabilities, there's a ton of intricate stuff to support the full matrix of LAS format permutations. It would add a ton of complexity.
