### ISSUE TITLE
CMake build throws error about lazperf

### ISSUE THREAD

**Issue by mihir3445** [hobu/laz-perf#77]
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at cmake/install.cmake:22 (install):
  install TARGETS given target "lazperf" which does not exist in this
  directory.
Call Stack (most recent call first):
  cpp/CMakeLists.txt:42 (include)

**Comment by mihir3445** [comment]
cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by abellgithub** [comment]
It appears that you were trying to build from the `cpp` subdirectory. This isn't supported and isn't necessary. Build from the top level and all should be well.
