### ISSUE TITLE
CMake configuration with gtest is incorrect

### ISSUE THREAD

**Issue by hobu** [hobu/laz-perf#89]
The Conda Forge builds are failing due to incorrect CMake configuration in the latest release:

```
CMake Error at cpp/test/CMakeLists.txt:15 (add_subdirectory):
  The source directory

    /Users/runner/miniforge3/conda-bld/laz-perf_1623102252085/work/cpp/test/gtest/gtest-02-06-2021

  does not contain a CMakeLists.txt file.


```

See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=334297&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b for detailed errors.

**Comment by abellgithub** [comment]
This seems to have been fixed.
