### ISSUE TITLE
Laz files with more than 1 chunk created by lazperf-2.0.5 cause lazip to assert

### ISSUE THREAD

**Issue by froody** [hobu/laz-perf#96]
In lazperf-1.4.4, there was some code to special-case the first chunk, and this had the effect of setting the size of the first chunk to the delta between the offest of the first point and the end of the chunk. See https://github.com/hobu/laz-perf/blob/1.4.4/laz-perf/io.hpp#L869-L872

In lazperf-2.0.5 however, the logic was refactored, and now the first chunk size is equal to `offset - chunk_state.last_chunk_write_offset`, where is `chunk_state.last_chunk_write_offset=0` at the end of the first chunk. See https://github.com/hobu/laz-perf/blob/2.0.5/cpp/lazperf/io.cpp#L419-L421

This triggers an exception in laszip when decoding files with multiple chunks, but doesn't affect laz-perf since it doesn't actually check chunk sizes when decoding. See lazip code [here](https://github.com/LASzip/LASzip/blob/master/src/lasreadpoint.cpp#L423-L428)

Proposed fix is to set `chunk_state.last_chunk_write_offset = f->tellp();` in [this block](https://github.com/hobu/laz-perf/blob/2.0.5/cpp/lazperf/io.cpp#L412-L413)

Note also that since the refactor, current_chunk_index is no longer updated/used.

**Comment by abellgithub** [comment]
I believe I have all of this fixed in a branch. If you want to share a test file I can confirm.

**Comment by abellgithub** [comment]
Fixed by #101
